server:
  port: 8081
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projecta?useSSL=false
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect